  sonarqube_master_job:
    stage: test
    only:
      - master
    script:
      - sonar-scanner -Dsonar.host.url=http://192.168.0.66:9000 -Dsonar.login=59d30fe3109241b1beb6db2744432d718d649796 -Dsonar.projectKey=$CI_PROJECT_ID:$CI_PROJECT_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
  sonarqube_preview_feature_job:
    stage: test
    except:
      - master
    script:
      - git checkout origin/master
      - git merge $CI_COMMIT_SHA --no-commit --no-ff
      - sonar-scanner -Dsonar.host.url=http://192.168.0.66:9000 -Dsonar.login=59d30fe3109241b1beb6db2744432d718d649796 -Dsonar.projectKey=$CI_PROJECT_ID:$CI_PROJECT_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
